=== herisn23/GameBookStories/story.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	xmlns:html="http://www.w3.org/1999/xhtml"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1"  >
	<xs:element name="story">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="androidDrawable" name="background" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Background of story</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element type="xs:int" name="version" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Version of story</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:sequence>
					<xs:element type="includeType" name="include" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:element type="charactersType" name="characters"  minOccurs="0" />
				<xs:element type="enemiesType" name="enemies"  minOccurs="0" />
				<xs:element type="sectionsType" name="sections"  minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="bonusState">
		<xs:restriction base="xs:string">
			<xs:enumeration value="before_fight">
				<xs:annotation>
					<xs:documentation>
						Bonus will be applied before fight.
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="after_fight">
				<xs:annotation>
					<xs:documentation>
						Bonus will be applied after fight.
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="normal">
				<xs:annotation>
					<xs:documentation>
						<html:p>Default value.</html:p>
						<html:p>When section has enemies this bonus will be ignored.</html:p>
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="attrType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="health" />
			<xs:enumeration value="defense" />
			<xs:enumeration value="luck" />
			<xs:enumeration value="skill" />
			<xs:enumeration value="attack" />
			<xs:enumeration value="damage" />
			<xs:enumeration value="skillpower" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="enemyLevelType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="boss" />
			<xs:enumeration value="minion" />
			<xs:enumeration value="creature" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="specialAttackType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="decrease_health_greater" />
			<xs:enumeration value="decrease_health_greater_overtime" />
			<xs:enumeration value="increase_attack" />
			<xs:enumeration value="life_leech" />
			<xs:enumeration value="increase_skill" />
			<xs:enumeration value="increase_health_greater_overtime" />
			<xs:enumeration value="increase_health" />
			<xs:enumeration value="cancel_positive" />
			<xs:enumeration value="increase_health_greater" />
			<xs:enumeration value="twice_attack" />
			<xs:enumeration value="quick_reaction" />
			<xs:enumeration value="decrease_health" />
			<xs:enumeration value="increase_defense" />
			<xs:enumeration value="decrease_skill" />
			<xs:enumeration value="increase_health_overtime" />
			<xs:enumeration value="decrease_attack" />
			<xs:enumeration value="decrease_health_overtime" />
			<xs:enumeration value="reflect_damage" />
			<xs:enumeration value="decrease_defense" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="androidDrawable">
		<xs:annotation>
			<xs:documentation>
				Text is android string reference and must have format "@drawable/([a-zA-Z0-9/_])*".
				<html:p>Example:</html:p>
				@drawable/any_image_in_app
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="@drawable/([a-zA-Z0-9/_])*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="skillsType">
		<xs:sequence>
			<xs:element type="skillType" name="skill" maxOccurs="unbounded" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="skillType">
		<xs:attribute type="specialAttackType" name="name" use="required"/>
		<xs:attribute type="xs:int" name="levelRequired" use="required"/>
	</xs:complexType>
	<xs:complexType name="characterType">
		<xs:sequence>
			<xs:element type="skillsType" name="skills" maxOccurs="1" minOccurs="1">
				<xs:annotation>
					<xs:documentation>Section of story</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="attrType" name="primaryStat" />
			<xs:element type="xs:int" name="health" />
			<xs:element type="xs:int" name="defense" />
			<xs:element type="xs:int" name="skill" />
			<xs:element type="xs:int" name="luck" />
			<xs:element type="xs:int" name="attack" />
			<xs:element type="xs:int" name="baseDamage" minOccurs="0" maxOccurs="1"/>
			<xs:element type="xs:int" name="skillPower" />
		</xs:sequence>
		<xs:attribute type="xs:int" name="position" use="required">
			<xs:annotation>
				<xs:documentation>Start section position of character
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:int" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" use="required">
			<xs:annotation>
				<xs:documentation>Name of character</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="description" use="required">
			<xs:annotation>
				<xs:documentation>Description of character</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="charactersType">
		<xs:sequence>
			<xs:element type="characterType" name="character" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="includeType">
		<xs:attribute type="xs:string" name="name" use="required" />
	</xs:complexType>
	<xs:complexType name="bonusType">
		<xs:attribute type="attrType" name="type" use="optional" />
		<xs:attribute type="xs:boolean" name="base" use="optional" />
		<xs:attribute type="xs:int" name="value" use="optional" />
		<xs:attribute type="xs:boolean" name="permanent" use="optional">
			<xs:annotation>
				<xs:documentation>
					Default is TRUE. Non permament bonuses works only when fighting.
					Before battle will be added and after fight will be removed.
					When permanent is false, then bonusState is ignored.
					When stats are removed while bonus is not permanent then stats are not overflow value before bonus application.
					Ex.: Skill before fight is 5, nonpermanent bonus is 20 but character can have only max 20 skill.
					After fight skill will be returned to 5.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:boolean" name="debuff" use="optional" >
			<xs:annotation>
				<xs:documentation>
					This bonus has negative effect.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="bonusState" name="state" use="optional" >
			<xs:annotation>
				<xs:documentation>
					Define when bonus will be aplied.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:boolean" name="overflowed" use="optional" >
			<xs:annotation>
				<xs:documentation>
					This bonus can overflow character default attribute.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="bonusesType">
		<xs:sequence>
			<xs:element type="bonusType" name="bonus" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="refType">
		<xs:attribute type="xs:string" name="value" use="required" />
		<xs:attribute type="specialAttackType" name="overrideSkill" use="optional" />
		<xs:attribute type="xs:float" name="xpcoeff" use="optional" />
	</xs:complexType>
	<xs:complexType name="enemiesRefType">
		<xs:sequence>
			<xs:element type="refType" name="ref" maxOccurs="unbounded"
				minOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="enemyType">
		<xs:sequence>
			<xs:element type="skillsType" name="skills" maxOccurs="1" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Section of story</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="xs:int" name="skillPower" minOccurs="0"/>
			<xs:element type="xs:int" name="health" />
			<xs:element type="xs:int" name="defense" />
			<xs:element type="xs:int" name="skill" />
			<xs:element type="xs:int" name="luck" />
			<xs:element type="xs:int" name="attack" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="name" use="required" />
		<xs:attribute type="xs:float" name="xpcoeff" use="optional" />
		<xs:attribute type="enemyLevelType" name="type" use="optional" />
		<xs:attribute type="xs:string" name="id" use="required" />
	</xs:complexType>
	<xs:complexType name="enemiesType">
		<xs:sequence>
			<xs:element type="enemyType" name="enemy" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="optionType">
				<xs:attribute type="xs:int" name="section" use="required">
					<xs:annotation>
						<xs:documentation>Position of next section.</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:string" name="text" use="required">
					<xs:annotation>
						<xs:documentation>Text is android string reference and must have format "@string/text".</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:boolean" name="disableWhenSelected" use="optional">
					<xs:annotation>
						<xs:documentation>
							This option will be disabled when is selected. 
							<html:p>(For example when player returns from "dangerous" section.)</html:p>
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:boolean" name="luckAspect" use="optional">
					<xs:annotation>
						<xs:documentation>This option will be displayed only when character has luck. </xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute type="xs:int" name="skill" use="optional">
					<xs:annotation>
						<xs:documentation>Required skill of character for display this option. </xs:documentation>
					</xs:annotation>
				</xs:attribute>
	</xs:complexType>
	<xs:complexType name="optionsType">
		<xs:sequence>
			<xs:element type="optionType" name="option" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sectionType" mixed="false">
		<xs:sequence>
			<xs:element type="bonusesType" name="bonuses" minOccurs="0" />
			<xs:element type="enemiesRefType" name="enemies" minOccurs="0" />
			<xs:element type="optionsType" name="options" minOccurs="0" />
		</xs:sequence>
		<xs:attribute type="xs:int" name="level" use="optional" />
		<xs:attribute type="xs:boolean" name="resetAttributes" use="optional" />
		<xs:attribute type="xs:boolean" name="resetPositiveAttributes" use="optional" />
		<xs:attribute type="xs:boolean" name="resetNegativeAttributes" use="optional" />
		<xs:attribute type="xs:float" name="xpcoeff" use="optional" />
		<xs:attribute type="xs:int" name="position" use="required" />
		<xs:attribute type="xs:float" name="scoreMultiplier" use="optional">
			<xs:annotation>
				<xs:documentation>This attribute is used only when attribute winSection="true".</xs:documentation>
			</xs:annotation>
		</xs:attribute>	
		
		<xs:attribute type="xs:string" name="alreadyVisitedText" use="optional">
			<xs:annotation>
				<xs:documentation>Text will be displayed when player already visited section. Default value is standard text.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="text" use="required">
			<xs:annotation>
				<xs:documentation>Part of text of story.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:boolean" name="luckDefeatEnemies" use="optional">
			<xs:annotation>
				<xs:documentation>If player has luck, then enemies are defeated.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="enemiesDefeatedText"
			use="optional">
			<xs:annotation>
				<xs:documentation>Text will shown when player defeated all enemies
					(this is required when enemies are defined).</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:string" name="luckText" use="optional">
			<xs:annotation>
				<xs:documentation>Text will shown when player has luck and avoid combat.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:boolean" name="loseSection" use="optional">
			<xs:annotation>
				<xs:documentation>Indicates this is end of game (last section).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:boolean" name="winSection" use="optional">
			<xs:annotation>
				<xs:documentation>Indicates this is end of game (last section).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="sectionsType">
		<xs:sequence>
			<xs:element type="sectionType" name="section" maxOccurs="unbounded" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Section of story</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	
</xs:schema>

=== herisn23/GameBookStories/stories/arena2/arena/characters.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../story.xsd">
    <characters>
        <character position="1" id="1" name="clerik" description="clerik_desc" skillBased="SKILL_POWER">
            <skills>
                <ref value="heal"/>
                <ref value="greater_heal"/>
                <ref value="heal_overtime_and_cancel"/>
                <ref value="heal_and_heal_overtime"/>
                
                <ref value="life"/>
                <ref value="quick"/>
                <ref value="reflect"/>
                <ref value="posion_dagger"/>
            </skills>
            <primaryStat>skillpower</primaryStat>
            <health>50</health>
            <defense>3</defense>
            <skill>3</skill>
            <luck>3</luck>
            <attack>5</attack>
            <baseDamage>1</baseDamage>
            <skillPower>10</skillPower>
        </character>
    </characters>
</story>

=== herisn23/GameBookStories/zombie_apocalypse/zombie_apocalypse_soldier.xml
<?xml version="1.0" encoding="UTF-8"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../story.xsd">
    <sections>
        <!-- SECTION 1 -->
        <section position="1" text="section1_text" alreadyVisitedText="section1_visited_text">
            <options>
                <option section="2" text="section1_option1_text"/>
                <option section="" text="section1_option2_text"/>
                <option section="" text="section1_option3_text"/>
            </options>
        </section>
        <!-- SECTION 2 -->
        <section position="2" text="section2_text" enemiesDefeatedText="section2_enemy_text" luckText="section2_luck_text">
            <enemies>
                <enemy name="e_livingdead">
                    <health>7</health>
                    <defense>4</defense>
                    <skill>2</skill>
                    <luck>1</luck>
                    <attack>4</attack>
                </enemy>
            </enemies>
            <options>
                <option section="3" text="section2_option1_text"/>
                <option section="1" text="section2_option_barracks_text"/>
            </options>
        </section>
        <!-- SECTION 3 -->
        <section position="3" text="section3_text" winSection="true" scoreMultiplier="2">
            <options>
                <option section="4" text="section3_option1_text"/>
                <option section="1" text="section2_option_barracks_text"/>
            </options>
        </section>
        <!-- SECTION 4 -->
        <section position="4" text="section4_text" enemiesDefeatedText="section4_enemy_text" luckText="section4_luck_text" luckDefeatEnemies="true">
            <enemies>
                <enemy name="e_livingdead">
                    <health>5</health>
                    <defense>3</defense>
                    <skill>1</skill>
                    <luck>1</luck>
                    <attack>4</attack>
                </enemy>
                <enemy name="e_nohander">
                    <health>4</health>
                    <defense>5</defense>
                    <skill>1</skill>
                    <luck>1</luck>
                    <attack>3</attack>
                </enemy>
            </enemies>
            <options>
                <option section="5" text="section4_option1_text"/>
                <option section="1" text="section2_option_barracks_text"/>
            </options>
        </section>
        <!-- SECTION 5 -->
        <section position="5" text="section5_text" alreadyVisitedText="section5_visited_text">
            <bonuses>
                <bonus type="health" value="3" debuff="true"/>
                <bonus type="luck" value="1" overflowed="true" />
            </bonuses>
            <options>
                <option section="6" text="section5_option1_text" disableWhenSelected="true" />
                <option section="8" text="section5_option2_text" />
                <option section="9" text="section5_option3_text" luckAspect="true" disableWhenSelected="true" />
            </options>
        </section>
        <!-- SECTION 6 -->
        <section position="6" text="section6_text">
            <options>
                <option section="5" text="section6_option1_text" />
                <option section="7" text="section6_option2_text" />
            </options>
        </section>
        <!-- SECTION 8 -->
        <section position="8" text="section8_text">
            <bonuses>
                <bonus type="health" value="1" />
            </bonuses>
            <options>
                <option section="10" text="section8_option1_text" />
                <option section="12" text="section8_option2_text" />
            </options>
        </section>
        <!-- SECTION 9 -->
        <section position="9" text="section9_text">
            <bonuses>
                <bonus type="skill" value="1" overflowed="true" />
            </bonuses>
            <options>
                <option section="5" text="section9_option1_text" />
            </options>
        </section>
        <!-- SECTION 11 -->
        <section position="11" text="section11_text">
            <bonuses>
                <bonus type="defense" value="1" overflowed="true" />
            </bonuses>
            <options>
                <option section="10" text="section11_option1_text" />
            </options>
        </section>
        
        
        <!-- enter to shared sections -->
        <!-- SECTION 7 -->
        <section position="7" text="section7_text">
            <bonuses>
                <bonus type="health" value="2" />
            </bonuses>
            <options>
                <option section="" text="@string/sg_continue" />
            </options>
        </section>
        <!-- SECTION 10 -->
        <section position="10" text="section10_text" alreadyVisitedText="section10_visited_text">
            <options>
                <option section="" text="section10_option1_text" />
                <option section="11" text="section10_option2_text" disableWhenSelected="true" luckAspect="true"/>
            </options>
        </section>
        <!-- SECTION 12 -->
        <section position="12" text="section12_text">
            <options>
                <option section="" text="section12_option1_text" />
            </options>
        </section>
    </sections>
</story>

=== herisn23/GameBookStories/stories/arena2/arena/enemies/bosses.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../../story.xsd">
    <enemies>
        <enemy skillBased="ATTACK" name="test_enemy" id="test_enemy">
            <skills>
                <ref value=""/>
            </skills>
            <skillPower>2</skillPower>
            <health>50</health>
            <defense>25</defense>
            <skill>5</skill>
            <luck>5</luck>
            <attack>5</attack>
        </enemy>
    </enemies>
</story>

=== herisn23/GameBookStories/stories/zombie_apocalypse/zombie_apocalypse_characters.xml
<?xml version="1.0" encoding="UTF-8"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../story.xsd">
    <characters>
        <character position="1" id="1" name="ch_soldier" description="dsc_soldier">
            <health>15</health>
            <defense>5</defense>
            <skill>2</skill>
            <luck>1</luck>
            <attack>7</attack>   
        </character>
        <character position="" id="2" name="ch_doctor" description="dsc_doctor">
            <health>25</health>
            <defense>2</defense>
            <skill>1</skill>
            <luck>1</luck>
            <attack>7</attack>
        </character>
        <character position="" id="3" name="ch_policeman" description="dsc_policeman">
            <health>15</health>
            <defense>2</defense>
            <skill>5</skill>
            <luck>1</luck>
            <attack>7</attack>
        </character>
        <character position="" id="4" name="ch_homeless" description="dsc_homeless">
            <health>10</health>
            <defense>1</defense>
            <skill>2</skill>
            <luck>8</luck>
            <attack>7</attack>
        </character>
    </characters>
</story>

=== herisn23/GameBookStories/zombie_apocalypse/zombie_apocalypse_characters.xml
<?xml version="1.0" encoding="UTF-8"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../story.xsd">
    <characters>
        <character position="1" id="1" name="@string/story1_ch_soldier" description="@string/story1_dsc_soldier">
            <health>15</health>
            <defense>5</defense>
            <skill>2</skill>
            <luck>1</luck>
            <attack>7</attack>   
        </character>
        <character position="" id="2" name="@string/story1_ch_doctor" description="@string/story1_dsc_doctor">
            <health>25</health>
            <defense>2</defense>
            <skill>1</skill>
            <luck>1</luck>
            <attack>7</attack>
        </character>
        <character position="" id="3" name="@string/story1_ch_policeman" description="@string/story1_dsc_policeman">
            <health>15</health>
            <defense>2</defense>
            <skill>5</skill>
            <luck>1</luck>
            <attack>7</attack>
        </character>
        <character position="" id="4" name="@string/story1_ch_homeless" description="@string/story1_dsc_homeless">
            <health>10</health>
            <defense>1</defense>
            <skill>2</skill>
            <luck>8</luck>
            <attack>7</attack>
        </character>
    </characters>
</story>

=== herisn23/GameBookStories/stories/zombie_apocalypse/characters_lines/policeman_line.xml
<?xml version="1.0" encoding="UTF-8"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../story.xsd">
    <sections>
        <section position="47" text="section47_text" enemiesDefeatedText="section47_enemy_text" luckDefeatEnemies="true" luckText="section47_luck_text">
            <enemies>
                <ref value="dead_policeman"/>
            </enemies>
            <options>
                <option section="48" text="section47_option1_text"></option>
            </options>
        </section>
        <section position="48" text="section48_text" enemiesDefeatedText="section48_enemy_text" luckText="section48_luck_text">
            <enemies>
                <ref value="dead_policeman"/>
                <ref value="dead_policeman"/>
                <ref value="dead_policeman"/>
            </enemies>
            <options>
                <option section="49" text="section48_option1_text"></option>
            </options>
        </section> 
        <section position="49" text="section49_text">
            <options>
                <option section="50" text="section49_option1_text"></option>
                <option section="51" text="section49_option2_text"></option>
            </options>
        </section>
        <section position="50" text="section50_text">
            <bonuses>
                <bonus overflowed="true" type="health" value="20" />
            </bonuses>
            <options>
                <option section="52" text="section50_option1_text"></option>
            </options>
        </section> 
        <section position="51" text="section51_text">
            <bonuses>
                <bonus overflowed="true" type="attack" value="2" />
                <bonus overflowed="true" type="skill" value="1" />
            </bonuses>
            <options>
                <option section="53" text="section51_option1_text"></option>
            </options>
        </section>
        <section position="52" text="section52_text">
            <options>
                <option section="54" text="section52_option1_text"></option>
            </options>
        </section>
        <section position="53" text="section53_text">
            <options>
                <option section="54" text="section53_option1_text"></option>
            </options>
        </section>
        <section position="54" text="section54_text">
            <options>
                <option section="55" text="section54_option1_text"></option>
            </options>
        </section>
        <section position="55" text="section55_text">
            <options>
                <option section="56" text="section55_option1_text" ></option>
                <option section="" text="section55_option2_text" skill="11"></option>
            </options>
        </section>
        <section position="56" text="section56_text">
            <options>
                <option section="" text="section56_option1_text" ></option>
                <option section="" text="section56_option2_text" ></option>
            </options>
        </section>
    </sections>
</story>

=== herisn23/GameBookStories/stories/zombie_apocalypse/enemies/bosses.xml
<?xml version="1.0" encoding="UTF-8"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../../story.xsd">
    <enemies>
        <enemy name="e_brain_eater" id="brain_eater" type="boss">
            <specialAttack>reflectDamage</specialAttack>
            <skillPower>1</skillPower>
            <health>40</health>
            <defense>5</defense>
            <skill>5</skill>
            <luck>5</luck>
            <attack>6</attack>
        </enemy>
    </enemies>
</story>

=== herisn23/GameBookStories/stories/zombie_apocalypse/mini_bosses.xml
<?xml version="1.0" encoding="UTF-8"?>
<story xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../story.xsd">
    <enemies>
        <enemy name="e_rotten_merchant" id="rotten_merchant">
           <health>20</health>
           <defense>3</defense>
           <skill>2</skill>
           <luck>3</luck>
           <attack>7</attack>
       </enemy>
    </enemies>
</story>
